#!/usr/bin/python
# -*- coding: utf-8 -*-

OPL_TEMPLATE = """
/************************************************************************************
* Type: Instance for the quay crane scheduling problem
* Generated by qcspgen.py, author: Chen Jiang Hang
* Based on QCSPgen, author: Frank Meisel
************************************************************************************/

// number of tasks n, number of bays b
n = {n};
b = {b};

// task index i, processing times p, and bay locations l
//i = {t_index}
p = {p};
l = {l};

// set of precedence constrained task pairs Phi
Phi = {Phi};

// set of non-simultaneous task pairs Psi
Psi = {Psi};

// number of cranes q
q = {q};

// crane index k, ready times r, initial bay locations l0
//k = {q_index}
r = {r};
l0 = {l0};

// travel time t, safety margin s
t = {t};
s = {s};

// - end of file -
"""

JSON_TEMPLATE = """
{{
    "header" : "Type: Instance for the quay crane scheduling problem. Generated by qcspgen.py, author: Chen Jiang Hang. Based on QCSPgen, author: Frank Meisel",
    "n" : {n},
    "b" : {b},
    "p" : {p},
    "l" : {l},
    "Phi" : {Phi},
    "Psi" : {Psi},
    "q" : {q},
    "r" : {r},
    "l0" : {l0},
    "t" : {t},
    "s" : {s}
}}
"""

if __name__ == "__main__":
    pass
